title: Napoleon's Nightmare
theme: just-the-docs
url: http://www.napoleonsnightmare.com
color_scheme: dark
aux_links:
  Discord: https://discord.gg/qaV6KJkeHm
  itch.io: https://jaime-gonzalez-vallejo.itch.io/napoleons-nightmare
  GitHub: https://github.com/JimmyHammer/napoleons-nightmare
aux_links_new_tab: true
logo: "/assets/images/logo.png"
favicon_ico: "/assets/images/favicon.ico"
search:
  button: true

# Footer content
back_to_top: true
back_to_top_text: "Back to top"
footer_content: "The text on this page is licensed under <a href=\"https://creativecommons.org/licenses/by-sa/4.0\">CC-BY-SA 4.0.</a>"
last_edit_timestamp: true 